# Generated by Django 4.2.3 on 2023-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Active', models.BooleanField(default=False)),
                ('Location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
