# Generated by Django 4.2.5 on 2023-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_recog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmployeeID", models.IntegerField()),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("autoID", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeeID", models.IntegerField()),
                ("Name", models.CharField(max_length=255)),
                ("DateTime", models.DateTimeField()),
                ("CameraNo", models.IntegerField()),
                ("Image", models.ImageField(upload_to="transaction_images/")),
            ],
        ),
    ]
