# Generated by Django 4.2.5 on 2024-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_recog", "0002_employeeinfo_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="Image",
            field=models.ImageField(upload_to=""),
        ),
    ]
